apiVersion: v1
kind: Service
metadata:
  name: myjavaapp-svc
  labels:
    app: myjavaapp
    version: 2.6.2   # ✅ Updated to match pod label
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
      protocol: TCP
  selector:
    app: myjavaapp
    version: 2.6.2   # ✅ Updated to match pod label

 